# Generated by Django 2.0.3 on 2018-04-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inventory_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inventory_status',
            field=models.IntegerField(null=True),
        ),
    ]
