# Generated by Django 2.0.2 on 2018-04-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_transaction_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='lot_id',
            field=models.ForeignKey(on_delete=False, to='marketplace.Lot'),
        ),
    ]
