# Generated by Django 2.0.2 on 2018-04-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20180409_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.Lot'),
        ),
    ]
