# Generated by Django 2.0.3 on 2018-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20180409_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='information',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
