# Generated by Django 2.0.3 on 2018-04-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20180410_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_buyer_id',
            new_name='user_buyer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='username_buyer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='username_seller',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
