# Generated by Django 2.0.3 on 2018-05-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_profile_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
