# Generated by Django 2.0.3 on 2018-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('money', models.IntegerField()),
                ('level', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=255)),
                ('inventory_status', models.IntegerField()),
                ('inventory_capacity', models.IntegerField()),
            ],
        ),
    ]
