# Generated by Django 2.0.3 on 2018-04-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20180408_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
